# Generated by Django 2.1.7 on 2019-02-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('con_password', models.CharField(max_length=15)),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
