# Generated by Django 2.1.7 on 2019-02-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190213_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='image',
            field=models.ImageField(default=False, upload_to='MyImages'),
        ),
    ]
