# Generated by Django 2.1.7 on 2019-02-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userregister_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='gender',
        ),
    ]
