# Generated by Django 2.1.7 on 2019-02-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_userregister_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='image',
            field=models.ImageField(upload_to='MyImages'),
        ),
    ]
