# Generated by Django 2.1.7 on 2019-02-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190213_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='image',
            field=models.ImageField(upload_to='prasad'),
        ),
    ]
