# Generated by Django 2.1.7 on 2019-02-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
