# Generated by Django 2.1.7 on 2019-02-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190213_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproperty',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('property', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.ImageField(upload_to='propertyImages')),
            ],
        ),
    ]
