# Generated by Django 2.1.7 on 2019-02-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_addproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='property_id',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addproperty',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
